#
# Pimoroni Pico Display Pack 2.0 (320 x 240 ST7789)
# https://shop.pimoroni.com/products/pico-display-pack-2-0
# https://botland.store/search?s=PIM-20896
#
target_compile_definitions(firmware PRIVATE
    MIPI_DISPLAY_PIN_CS=17
    MIPI_DISPLAY_PIN_DC=16
    MIPI_DISPLAY_PIN_RST=-1
    MIPI_DISPLAY_PIN_BL=20
    MIPI_DISPLAY_PIN_CLK=18
    MIPI_DISPLAY_PIN_MOSI=19
    MIPI_DISPLAY_PIN_MISO=-1
    MIPI_DISPLAY_PIN_POWER=-1
    MIPI_DISPLAY_PIN_TE=-1

    MIPI_DISPLAY_SPI_PORT=spi0
    MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ=62500000

    # Horizontal
    MIPI_DISPLAY_ADDRESS_MODE=MIPI_DCS_ADDRESS_MODE_RGB|MIPI_DCS_ADDRESS_MODE_SWAP_XY|MIPI_DCS_ADDRESS_MODE_MIRROR_X
    MIPI_DISPLAY_WIDTH=320
    MIPI_DISPLAY_HEIGHT=240
    MIPI_DISPLAY_OFFSET_X=0
    MIPI_DISPLAY_OFFSET_Y=0

    # Vertical
    # MIPI_DISPLAY_PIXEL_FORMAT=MIPI_DCS_PIXEL_FORMAT_16BIT
    # MIPI_DISPLAY_ADDRESS_MODE=MIPI_DCS_ADDRESS_MODE_RGB
    # MIPI_DISPLAY_WIDTH=240
    # MIPI_DISPLAY_HEIGHT=320
    # MIPI_DISPLAY_OFFSET_X=0
    # MIPI_DISPLAY_OFFSET_Y=0

    MIPI_DISPLAY_INVERT=1
)