#
# Waveshare 1.14inch LCD Module (240x135 ST7789VW)
# https://www.waveshare.com/wiki/1.14inch_LCD_Module
#
target_compile_definitions(firmware PRIVATE
    MIPI_DISPLAY_PIN_CS=3
    MIPI_DISPLAY_PIN_DC=5
    MIPI_DISPLAY_PIN_RST=4
    MIPI_DISPLAY_PIN_BL=13
    MIPI_DISPLAY_PIN_CLK=14
    MIPI_DISPLAY_PIN_MOSI=15
    MIPI_DISPLAY_PIN_MISO=-1
    MIPI_DISPLAY_PIN_POWER=-1
    MIPI_DISPLAY_PIN_VSYNC=-1

    MIPI_DISPLAY_SPI_PORT=spi1
    MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ=62500000

    MIPI_DISPLAY_PIXEL_FORMAT=MIPI_DCS_PIXEL_FORMAT_16BIT
    MIPI_DISPLAY_ADDRESS_MODE=MIPI_DCS_ADDRESS_MODE_RGB
    # MIPI_DISPLAY_ADDRESS_MODE=MIPI_DCS_ADDRESS_MODE_RGB|MIPI_DCS_ADDRESS_MODE_SWAP_XY|MIPI_DCS_ADDRESS_MODE_MIRROR_X
    MIPI_DISPLAY_WIDTH=135
    MIPI_DISPLAY_HEIGHT=240
    MIPI_DISPLAY_OFFSET_X=52
    MIPI_DISPLAY_OFFSET_Y=40
    MIPI_DISPLAY_INVERT=1
)